### ISSUE TITLE
Checklist for CA.kt

### ISSUE THREAD

**Issue by shiraji** [shiraji/KotlinConf2017#10]
- [x] Use newest slide
- [x] Hide Dock (Right click dock and "Turn hiding on"
- [x] Do not disturb mode (Click top right corner)
- [x] Clear desktop icons (`defaults write com.apple.finder CreateDesktop -boolean false; killall Finder`)

**Comment by shiraji** [comment]
Done
